init:
  target:
    URL: ssh://127.0.0.1
    credentials: dev
pipeline:
  task1:
    action: workflow.print
    message: Hello World
  task2:
    action: exec:run
    target: $target
    commands:
      - echo 'Hello World'