init:
  name: $params.name
pipeline:
  task1:
    action: workflow.print
    message: Hello World $name
    description: print hello
  task2:
    description: test subtasks
    subTask1:
      action: print
      message: subTask 1 $params.key1
    subTask2:
      action: print
      message: subTask 2 $params.name
  task3:
    description: print bye
    action: print
    message: Bye $name