init:
  target:
    URL: ssh://127.0.0.1
    credentials: dev
  name: $params.name
pipeline:
  task1:
    action: print
    message: Hello World $name
  task2:
    action: exec:run
    target: $target
    commands:
      - echo 'Hello World $name'