init:
  target:
    url:  ssh://127.0.0.1/
    credentials: dev
defaults:
  target: $target
pipeline:
  task1:
    action: storage:copy
    request: '@copy'
  task2:
    action: exec:run
    commands:
      - ls -al /tmp/README.md