pipeline:
  task1:
    inspect:
      action: docker:inspect
      '@name': endly
      logging: false
    ipInfo:
      action: print
      message: ${inspect.Info[0].NetworkSettings.IPAddress}
    networkInfo:
      action: print
      message: $AsJSON(${inspect.Info[0].NetworkSettings.Networks})
  task2:
    inspect:
      action: docker:inspect
      '@name': endly
      ':name': endlyInfo
      logging: false
    ipInfo:
      action: print
      message: ${endlyInfo.Info[0].NetworkSettings.IPAddress}
    networkInfo:
      action: print
      message: $AsJSON(${endlyInfo.Info[0].NetworkSettings.Networks})
